title: dnd repository
email: tjheslin1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A repository of characters, maps and adventures for Dungeond & Dragons.
baseurl: "/dndrepository" # the subpath of your site, e.g. /blog
url: "http://tjheslin1.github.io"
github_username:  tjheslin1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
