title: dnd repository
email: tjheslin1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of characters, maps and adventures for Dungeons & Dragons
baseurl: "/dndrepository" # the subpath of your site, e.g. /blog
url: "http://tjheslin1.github.io"
github_username:  tjheslin1
source-url: "https://github.com/tjheslin1/dndrepository"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
